networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/aspnet_local.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8000:80
  frontend:
    build:
      context: ../Angular
      dockerfile: ../.docker/aspnet.dockerfile
    networks:
      - locally
    ports:
      - 4200:4200

  data:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:12
    networks:
      - locally

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9411:9411

version: '3.8'
